// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package fir_addrmap_pkg;

    localparam FIR_ADDRMAP_DATA_WIDTH = 32;
    localparam FIR_ADDRMAP_MIN_ADDR_WIDTH = 9;
    localparam FIR_ADDRMAP_SIZE = 'h114;

    typedef struct {
        logic [15:0] next;
    } fir_regfile__CSR__CODE__in_t;

    typedef struct {
        fir_regfile__CSR__CODE__in_t CODE;
    } fir_regfile__CSR__in_t;

    typedef struct {
        fir_regfile__CSR__in_t CSR;
    } fir_regfile__in_t;

    typedef struct {
        fir_regfile__in_t FIR;
    } fir_addrmap__in_t;

    typedef struct {
        logic [31:0] value;
    } fir_regfile__filter_depth__VALUE__out_t;

    typedef struct {
        fir_regfile__filter_depth__VALUE__out_t VALUE;
    } fir_regfile__filter_depth__out_t;

    typedef struct {
        logic [31:0] value;
    } fir_regfile__mem_addr__ADDR__out_t;

    typedef struct {
        fir_regfile__mem_addr__ADDR__out_t ADDR;
    } fir_regfile__mem_addr__out_t;

    typedef struct {
        logic [15:0] value;
    } fir_regfile__mem_data__DATA__out_t;

    typedef struct {
        fir_regfile__mem_data__DATA__out_t DATA;
    } fir_regfile__mem_data__out_t;

    typedef struct {
        logic value;
    } fir_regfile__we_strb__STRB__out_t;

    typedef struct {
        fir_regfile__we_strb__STRB__out_t STRB;
    } fir_regfile__we_strb__out_t;

    typedef struct {
        fir_regfile__filter_depth__out_t filter_depth;
        fir_regfile__mem_addr__out_t mem_addr;
        fir_regfile__mem_data__out_t mem_data;
        fir_regfile__we_strb__out_t we_strb;
    } fir_regfile__out_t;

    typedef struct {
        fir_regfile__out_t FIR;
    } fir_addrmap__out_t;
endpackage
